### ISSUE TITLE
Mocking ssh-add

### ISSUE THREAD

**Issue by edouard-lopez** [fisherman/mock#1]
As suggested int  [How to test ssh-add?](https://github.com/fisherman/fishtape/issues/22#issuecomment-250169268) I try to mock `ssh-add`, but here is what I got

```
mock ssh-add 0 'pom'
set: Invalid character “-” in variable name. Only alphanumerical characters and underscores are valid ina variable name.
~/.config/fish/functions/mock.fish (line 13):     set -g $result_var $result
                                                  ^
in function “mock”
        called on standard input
        with parameter list “ssh-add 0 pom”
```
### full test

[commit](https://github.com/edouard-lopez/fish-ssh-agent-1/commit/d1fdebd53c221cc0101790d4c9d9900fe0caaf62)

```
test "$TEST - Add a given key (with mock)"
  (
      eval (ssh-agent -c) > /dev/null
      ssh-keygen -f $path/.test -N '' >/dev/null

      mock ssd-add 0 "Identity added: /.test"
      __add_keys $path/.test.pub
      cat /tmp/ssh-add.err
    ) = 1
end
```

**Comment by Markcial** [comment]
nice catch, i will write tests so the vars can contain all valid function names, thanks for reporting the issue. I will ping you back when i get it fixed. :smile:

**Comment by Markcial** [comment]
Already solved on https://github.com/fisherman/mock/issues/2 Thanks!
